---
apiVersion: v1
data:
  mapRoles: >
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::650251705877:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-tlJdKJ87fN4T
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::650251705877:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1362"
  uid: fbba4746-0d01-445a-a7d8-f93c8c1c84b1
