---
apiVersion: v1
data:
  mapRoles: >
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::285432151339:role/eksctl-simple-jwt-api-cluster-ServiceRole-ZLpnR8fgvxAb
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::285432151339:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
